Data:
  root: Dataset/DVSGesture/
  data_file: C11W05.h5
  map_file: map.csv
  scene: lab # 'fluorescent_led', 'fluorescent', 'natural', 'led', 'lab', 'all'
  num_samples: null # 1000
  enhance_samples: 500 # 1000
  num_classes: 10
  form: Clip
  num_point: 1024
  clip_size: [2, 16, 128, 128] # CxTxHxW
  vox_size: [2, 16, 128, 128] # CxTxHxW
  split_by: time # just for clip
  ord: txyp

Model:
  name: Co_Model_3D #'i3d', 'pointnet2_msg', 'Co_Model_3D', 'Co_Model_2D', 'resnet34', 'resnet3d', 'gait2d', 'gait3d'
  nIter: 1
  noise: 1
  enhance: True
  enhance_checkpoint: 'Log/Enhance/Zero_Enhance/10121851/checkpoint.pkl'

Train:
  file_list: train.csv
  lr: 1.e-4
  weight_decay: 1.e-4
  num_epochs: 25
  batch_size: 32
  shuffle: True
  num_workers: 4
  drop_last: True

Test:
  file_list: test.csv
  batch_size: 32
  scenes: ['fluorescent_led', 'fluorescent', 'natural', 'led', 'lab', 'all']

Recorder:
  log_dir: 'Output'
  save_log: True
  show_visdom: True
  show_tensorboard: False
